---
title: "CC Power Analysis"
author: "Brian Gural"
date: "2023-10-03"
output: html_document
---

```{r load libs}
libs <- c("tidyverse", "Seurat", "SeuratDisk", "SCpubr", "Biobase",  
          "reshape2", "ggmagnify", "compositions", "patchwork", "sparcc", "RColorBrewer") # list libraries here
lapply(libs, require, character.only = T)
rm(libs)
```


```{r load data}
# Define the URL the cached allele frequencies from SPARCC
url <- "https://github.com/gkeele/sparcc_cache/archive/refs/heads/master.zip"

# Load the RData file directly from the URL

#download.file(url = url, destfile = "data/raw/power_est/sparcc_cache.zip") 
#unzip("data/raw/power_est/sparcc_cache.zip",
#      exdir = "data/processed/power_est")

```

```{r test to compare allele number}
two.allele <- sparcc::interpolate.table(sparcc::r1.dat, 
                                  num.replicates=6,
                                  strain.effect.size=0,
                                  n.alleles=2)
eight.allele <- sparcc::interpolate.table(sparcc::r1.dat, 
                                  num.replicates=6,
                                  strain.effect.size=0,
                                  n.alleles=8)
```



```{r}
#devtools::install_github("gkeele/sparcc")
#library(sparcc)


#set number of replicates [1+], proportion of variance explained by strain effect [0-1], and number of functional alleles [2,3,8]
#remember that assumptions about strain effect size influence power; higher h.strain = less benefit from replicates
#error variance = 1 - h.strain - h.qtl
num.replicates <- 4
n.alleles <- 2
qtl.effect.sizes <- unique(r1.dat$h.qtl)

#interpolate power, display subset for number of strains [10-70 by 5, 72]
power.at <- function(h2, n.alleles){
  df <- sparcc::interpolate.table(sparcc::r1.dat, 
                                  num.replicates=num.replicates,
                                  strain.effect.size=h2,
                                  n.alleles=n.alleles)
  df[df$n.strains==70,]
}
power.table <- function(n.alleles){
  tab <- data.frame(h.qtl=qtl.effect.sizes)
  tab$strain.0 <- round(power.at(0, n.alleles)$power.window*100, 0) 
  
  tab <- data.frame(power.window = round(power.at(0, n.alleles)$power.window*100, 0),
                          n.alleles = power.at(0, n.alleles)$n.alleles,
                          h.qtl = power.at(0, n.alleles)$h.qtl,
                          h2 = "zero")
  
  strain.15 <- data.frame(power.window = round(power.at(.15, n.alleles)$power.window*100, 0),
                          n.alleles = power.at(.15, n.alleles)$n.alleles,
                          h.qtl = power.at(.15, n.alleles)$h.qtl,
                          h2 = 0.15)
  
  strain.30 <- data.frame(power.window = round(power.at(.3, n.alleles)$power.window*100, 0),
                          n.alleles = power.at(.3, n.alleles)$n.alleles,
                          h.qtl = power.at(.3, n.alleles)$h.qtl,
                          h2 = 0.3)
  tab <- tab |> 
         rbind(strain.15) |> 
         rbind(strain.30)
  tab
}
power.range <- lapply(c(2), function(x){
  power.table(x)
}) |> 
  bind_rows() |> 
  pivot_wider(id_cols = c(h.qtl,n.alleles), names_from = h2, values_from = power.window)

power.range[is.na(power.range)] <- 100

power.dat.4 <- power.range |> 
              pivot_longer(cols = c("zero", "0.15", "0.3"))

# add labels and label coordinates
power.dat.4 <-  power.dat.4 |> 
              group_by(name, n.alleles) |> 
              arrange(desc(value)) |> 
              slice_head(n = 16)  |> 
              arrange(value) |> 
              slice_head(n = 1)  |> 
              mutate(label = case_when(
                        str_detect(name, "zero") ~ "No variance within strains",
                        str_detect(name, ".15") ~ "15% variance within strains",
                        str_detect(name, ".3") ~ "30% variance within strains")) |> 
              right_join(power.dat.4) |> 
              mutate(n.reps = 4)

```

```{r plot power, fig.width=20, fig.height= 8}

palette <- brewer.pal(3, "Dark2")
palette <- palette[c(2,3,1)]


n.four <- power.dat.4 |> 
ggplot(aes(x = h.qtl, y = value, group = name, color = name)) +
  geom_smooth(method = "loess", 
              linewidth = 4.5,
              color = "black",
              alpha = 0.2,
              fill = "black",
              span = 0.2) + 
  geom_smooth(method = "loess", 
              linewidth = 3, 
              alpha = 0.2,
              fill = "black",
              span = 0.2) +
  geom_hline(yintercept = 80, linetype = "dashed", alpha = 0.7, size = 1.4) +
  scale_fill_brewer(palette = "Dark2") +
  scale_color_brewer(palette = "Dark2") +
  #scale_color_manual(values = palette) +
  labs(x = "QTL Effect Size",
       y = "Power",
       title = "4 replicates") +
  theme_minimal() +
  #facet_wrap(~n.alleles) +
  theme(text = element_text(size = 28),
        axis.title = element_text(size = 28),
        #title = element_text(size = 18, hjust = 0.5),
        legend.position = 'none',
        plot.margin = unit(c(0,-0.5,0.2,0.2), "cm"),
        panel.grid.minor = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank()) +
  coord_cartesian(clip = 'off') +
  ggrepel::geom_label_repel(aes(label = label, y = value),
                            family = "Spline Sans Mono",
                            xlim = c(0.99, 0.99),
                            ylim = c(30, 75),
                            # style segment
                            segment.curvature = .1,
                            segment.angle = 1,
                            segment.inflect = TRUE, 
                            direction = 'y',
                            arrow = arrow(length = unit(0.015, "npc")),
                            force_pull = 0.1,
                            force = 2,
                            size = 7,
                            color = "black", 
                            segment.color = "black",
                            segment.size = 1.4,
                            box.padding = 0,
                            label.padding = 0.8,
                            point.padding = 0.5, 
                            label.size = 0.4,
                            label.r = 1.2
) 

```

```{r}
num.replicates <- 8

power.range <- lapply(c(2), function(x){
  power.table(x)
}) |> 
  bind_rows() |> 
  pivot_wider(id_cols = c(h.qtl,n.alleles), names_from = h2, values_from = power.window)

power.range[is.na(power.range)] <- 100

power.dat <- power.range |> 
              pivot_longer(cols = c("zero", "0.15", "0.3"))

# add labels and label coordinates
power.dat <-  power.dat |> 
              group_by(name, n.alleles) |> 
              arrange(desc(value)) |> 
              slice_head(n = 17)  |> 
              arrange(value) |> 
              slice_head(n = 1)  |> 
              mutate(label = case_when(
                        str_detect(name, "zero") ~ "No variance within strains",
                        str_detect(name, ".15") ~ "15% variance within strains",
                        str_detect(name, ".3") ~ "30% variance within strains")) |> 
              right_join(power.dat) |> 
              mutate(n.reps = 8)
```
```{r merge rep sets}
# merge
power.dat <- rbind(power.dat, power.dat.4)

# add strain effect x rep interaction
power.dat <-power.dat |> 
      mutate(strain_rep = paste0(name, "-", n.reps))
  

```




```{r plot, fig.width=8, fig.height=6}
palette <- c("#fed976", "#fd8d3c", "#bcbddc", "#807dba", "#c7e9c0", "#74c476")
n.eight <- power.dat |> 
ggplot(aes(x = h.qtl, y = value, group = strain_rep, color = strain_rep)) +
  geom_smooth(method = "loess", 
              linewidth = 3,
              color = "black",
              alpha = 0.2,
              fill = "black",
              span = 0.2) + 
  geom_smooth(method = "loess", 
              linewidth = 2.5, 
              alpha = 0.1,
              fill = "black",
              span = 0.2) +
  geom_hline(yintercept = 80, linetype = "dashed", alpha = 0.5, size = 1.4) +
  scale_color_manual(values = palette) +
  #scale_color_manual(values = palette) +
  labs(x = "QTL Effect Size",
       y = "Power") +
  theme_minimal() +
  #facet_wrap(~n.alleles) +
  theme(text = element_text(size = 28),
        axis.title = element_text(size = 28),
        #title = element_text(size = 18, hjust = 0.5),
        legend.position = 'none',
        plot.margin = unit(c(0,-0.5,0.2,0.2), "cm")) +
  coord_cartesian(clip = 'off') 

n.eight
```

```{r plot power, fig.width=8, fig.height=14}

wrap_plots(n.four, n.eight, ncol= 1)

```
