---
title: "Annotating Rau-Patterson snRNAseq"
author: "Brian Gural"
date: "2023-09-13"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 10, message = F, warning = F, error = T)
```



```{r load libs}
libs <- c("tidyverse", "Seurat", "SeuratDisk", "SCpubr", "Biobase", "MuSiC", 
          "reshape2", "SingleCellExperiment") # list libraries here
lapply(libs, require, character.only = T)
rm(libs)
```

```{r load data}
sn <- LoadH5Seurat("data/processed/single_cell/merges/rau_patterson/09132023/doublets_below_3.h5seurat")

# Load bulk data
bulk <- read.csv("data/processed/bulk/cc/06222022/counts_summed_transcripts.csv", row.names = 1)

colnames(bulk) <- extract_numeric(colnames(bulk))


# Load fractions data

fractions <- read.csv("data/processed/bulk/cc/fractions/jensen_rau_froese_cpm", row.names = 1)
fractions.pheno <- read.csv("data/processed/bulk/cc/fractions/jensen_rau_froese_pheno", row.names = 1)

frac.keep <- fractions.pheno |> 
  subset(origin != "Jensen") |> 
  pull(id)


fractions <- fractions[,frac.keep]
fractions.pheno <- fractions.pheno |> 
                   subset(origin != "Jensen")

rm(frac.keep)
```

```{r merge bulks}
common.genes <- row.names(fractions)[row.names(fractions) %in% row.names(bulk)]


fractions <- fractions[common.genes,]
fractions <- 2^fractions

# Convert to 
bulk <- bulk[common.genes,]

 # Calculate the library size for each sample
lib_sizes <- matrixStats::colSums2(as.matrix(bulk))
cpm <- t(apply(bulk, 1, function(x) (x / lib_sizes) * 1e6)) 
cpm <- cpm + 0.0000001

# Calculate the library size for each sample


bulk.all <- cbind(cpm, fractions)

```

```{r scran find markers, fig.width = 7, fig.height= 8, echo=FALSE, message=FALSE, warning=FALSE}

# Update sn with annotations
sn.mark <- sn |>
      subset(idents = seq(0,4,1)) |> 
      subset(features = rownames(sn)[rownames(sn) %in% rownames(bulk.all)])

sn.sce <- sn.mark |> 
  as.SingleCellExperiment(assay = "RNA") |>
  as("SummarizedExperiment")

# Add gene names
rownames(sn.sce) <- rownames(sn.mark@assays$RNA@counts)

# Get markers based on expression ratios between clusters and 1vAll comparisons

scn.markers  <- scran::findMarkers(sn.sce, groups = Idents(sn.mark), pval.type = "all")


.getMarkers <- function(type){
marker <- scn.markers@listData[[type]] |>
  as.data.frame() |>
  arrange(FDR) |>
  slice_head(n = 25) |>
  dplyr::select(p.value, FDR, summary.logFC) |>
  mutate(celltype = type) |> 
  rownames_to_column(var = "gene")
return(marker)}

# Collapse list of data frames
all.markers <- lapply(levels(Idents(sn.mark)), function(x){.getMarkers(x)}) |>
               purrr::reduce(full_join)

all.markers |>
  group_by(celltype) |>
  arrange(desc(summary.logFC)) |>
  slice_head(n = 3) 

gc()
```

```{r print gene lists}

# Genes here are printed and manuallly entered into ToppGene
# https://toppgene.cchmc.org/
genes <- function(x){ all.markers |> 
                      subset(celltype == x) |> 
                      pull(gene) |> 
                      as.data.frame() |> 
                      print(row.names = F, print.keys = F)
}

genes(0)

cell.types <- c("Endothelial, Cor. Art.",
                "Cardiomyocytes",
                "Fibroblast, Mesen.",
                "Valve Cell, Mesen.",
                "Monocyte, Myeloid")
                #"SMC, Mesenchymal",
                #"Endothelial, Endocard.")
                #"Cardiac Neuron",
                #"unclear",#"?Matrix FB, Lung?"
                #"unclear",#"??EC, CA??"
                #"unclear")#"???")

names(cell.types) <- levels(sn.mark)
sn.mark <- RenameIdents(sn.mark, cell.types)
```

```{r plot cell types}
# Make and save visuals
p.clusters <- SCpubr::do_DimPlot(sn.mark,
                   label = T,
                   repel = T,
                   font.size = 14,
                   label.size = 4) + 
                 NoLegend() + 
                 ggtitle("Cell type annotations") +
                 theme(
                   plot.title = element_text(size = 14, hjust = 0.5))


png(file = "data/processed/single_cell/merges/rau_patterson/09132023/cell_types.png",
    width = 1000, 
    height = 700,
    units = "px")

p.clusters

dev.off()

```
```{r save data }
#SaveH5Seurat(sn, "data/processed/single_cell/merges/rau_patterson/09132023/cell_types_db_3")
```




```{r music}

bulk.es.exp <- bulk.all[all.markers$gene,] |> 
  sapply(as.integer) %>%
  ExpressionSet(assayData = .) |> 
  exprs()
row.names(bulk.es.exp) <- all.markers$gene


# Run MuSiC with subset genes

# Convert to SingleCellExperiment
sce <- as.SingleCellExperiment(sn.mark, assay = "RNA")
  
# Exclude specified clusters
cells <- levels(Idents(sn.mark))
cells <- cells[!(cells %in% c("unclear")) & !is.na(cells)]
  
# Use MuSiC to estimate cell type proportions
decon <- music_prop(bulk.mtx = bulk.es.exp, sc.sce = sce, markers = all.markers$gene,
                      clusters = "ident", samples = "orig.ident",
                      select.ct = cells)
  
# Turn MuSiC output into graph-friendly dataframe
decon.melt <- reshape2::melt(decon$Est.prop.weighted)
colnames(decon.melt) = c('Sub', 'CellType', 'Prop')

rm(decon)
rm(sce)
rm(cells)

write.csv(decon.melt, "results/composition_est/06222022/rau_patterson/09132023.csv", 
          row.names = F)

```

```{r scdc prep}
devtools::install_github("meichendong/SCDC")
library("SCDC")
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
