---
title: "Merge scRNAseq datasets for deconvolution"
author: "Brian Gural"
date: "2023-09-07"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 10, message = F, warning = F, error = T)
```

```{r load libs, message=FALSE, echo = T, warning=FALSE, results= 'hide', cache=FALSE}
libs <- c("Seurat", "ggplot2", "DESeq2", "patchwork","SeuratDisk", "MuSiC", "reshape2",
          "tidyverse", "SingleCellExperiment", "harmony", "SCpubr", 
          "AUCell", "viridis", "gplots", "scales", "ggrepel", "gridExtra", "scCustomize",
          "httr","matrixStats", "scran", "scuttle", "scater", "DropletUtils", "scDblFinder",
          "DeconvoBuddies", "readr", "SingleCellExperiment",
          "SummarizedExperiment", "Biobase", "ggmagnify", "stringr", "MuSiC",
          "ggforce", "DirichletReg", "readxl") # list libraries here
lapply(libs, require, character.only = T)

rm(libs)
```


```{r load data, message=FALSE, echo = T, warning = FALSE, cache = T, collapse = T}
# load individual seurats
dir <- "data/processed/single_cell/"

# Select for input data
origins <- c("wu", "martini", "rau", "tabula") |>
           paste(collapse = "|") 

files <-  filter(grepl(origins, list.files(dir)))

# Load the selected seurat files
sn <- lapply(files, function(x){LoadH5Seurat(paste0(dir, x))})

names(sn) <- lapply(strsplit(files, ".h5seurat"), "[[", 1)
```

```{r non rau processing}
sn$wu$PercentMito <- PercentageFeatureSet(sn$wu_2021, pattern = "^mt-")
sn$wu$PercentRibo <- PercentageFeatureSet(sn$wu_2021, pattern = "^Rpl|^Rps")
```


```{r raw processing}

ClusterSeurat <- function(seurat.obj,
                          subset = T,
                          min.rna.ft = 200,
                          max.rna.ft = 2500,
                          min.rna.ct = 800,
                          max.mt.pt  = 0.05,
                          regress.by = "orig.ident",
                          harmony    = T,
                          res        = 0.2,
                          nfeatures  = 2000,
                          drop.levels = FALSE){
  set.seed(100)
  if(subset == T){
    seurat.obj <- subset(seurat.obj, 
                         subset = nFeature_RNA   > min.rna.ft     & 
                                  nFeature_RNA   < max.rna.ft     &
                                  nCount_RNA     > min.rna.ct     &
                                  PercentMito   <= max.mt.pt)
  }
  seurat.obj <- seurat.obj |>
    NormalizeData(verbose = F) |>
    FindVariableFeatures(verbose = F, nfeatures = nfeatures) |>
    ScaleData(verbose = F) |>
    RunPCA(verbose = F) 
  
  if(harmony == T){
    if(drop.levels ==T){
    seurat.obj@meta.data[[regress.by]] <- droplevels(seurat.obj@meta.data[[regress.by]]) 
    }
    seurat.obj <- RunHarmony(seurat.obj, 
                             group.by.vars = regress.by,
                             verbose = F,
                             project.dim = F)
  }
  
  # find elbow
    # Determine percent of variation associated with each PC
    pct <- seurat.obj[["pca"]]@stdev / sum(seurat.obj[["pca"]]@stdev) * 100
    # Calculate cumulative percents for each PC
    cumu <- cumsum(pct)
    # Determine which PC exhibits cumulative percent greater than 90% and % variation associated with the PC as less than 5
    co1 <- which(cumu > 90 & pct < 5)[1]
    # Determine the difference between variation of PC and subsequent PC
    co2 <- sort(which((pct[1:length(pct) - 1] - pct[2:length(pct)]) > 0.1), decreasing = T)[1] + 1
    pcs <- min(co1, co2)
  
  if(harmony == T){
    seurat.obj <- seurat.obj |>
      FindNeighbors(dims = 1:pcs, reduction = "harmony", verbose = F) |>
      FindClusters(resolution = res, verbose = F) |>
      RunUMAP(dims = 1:pcs, reduction = "harmony", verbose = F)
    return(seurat.obj)
  }else{
    seurat.obj <- seurat.obj |>
      FindNeighbors(dims = 1:pcs, reduction = "pca", verbose = F) |>
      FindClusters(resolution = res, verbose = F) |>
      RunUMAP(dims = 1:pcs, reduction = "pca", verbose = F)
    return(seurat.obj)
  }}




sn <- lapply(sn, function(x){ClusterSeurat(x, max.rna.ft = 6000, subset = T, max.mt.pt = 5, harmony = F)})

# Add cluster info
.addClusters <- function(sn.func){
  sn.func$seurat.clusters <- Idents(sn.func)
  return(sn.func)
}

sn <- lapply(sn, function(x){.addClusters(x)})
```


```{r sn raw visuals, fig.height=22, fig.width=14}
plotUMAP <- function(data,
                     dim.ft = NULL,
                     feat.ft = NULL,
                     feat.labels =NULL,
                     vln.ft = NULL,
                     vln.groups = NULL,
                     width = NULL,
                     height = NULL,
                     ncol = NULL,
                     nrow = NULL,
                     design = NULL,
                     label.size = 4,
                     font.size = NULL,
                     name = NULL) {
  dim.plots  <- vector("list", length(dim.ft))
  feat.plots <- vector("list", length(feat.ft))
  vln.plots <- vector("list", length(vln.ft)*length(vln.groups))
  print(name)
  for(i in seq_along(dim.plots)){
    dim.plots[[i]]<- do_DimPlot(data, 
                             reduction = 'umap', 
                             group.by = dim.ft[[i]],
                             label = T,
                             repel = T,
                             font.size = font.size,
                             label.size = label.size) + 
                          NoLegend() + 
                          ggtitle(name) +
                          theme(plot.title = element_text(size = font.size*2, hjust = 0.5))
  } 
  
  for(i in seq_along(feat.plots)){
    feat.plots[[i]] <-  SCpubr::do_FeaturePlot(data, 
                                    reduction = "umap", 
                                    features = feat.ft[[i]],
                                    pt.size = 0.4, 
                                    order = TRUE,
                                    font.size = font.size,
                                    label.size = label.size) + 
                                    ggtitle(if(
                                      !is.null(feat.labels[[i]])){
                                        paste0("*",feat.ft[[i]],"*", ", ", feat.labels[[i]])
                                           }else{
                                        feat.ft[[i]]}) +
                                    theme(plot.title = ggtext::element_markdown())
  }
  for(i in seq_along(vln.ft)){
    for(j in seq_along(vln.groups)){
    vln.plots[[i*j]] <-  SCpubr::do_ViolinPlot(data, 
                                               features = vln.ft[[i]], 
                                               group.by = vln.groups[[j]],
                                               font.size = font.size) + 
                                               ggtitle(paste0(vln.ft[[i]], " by ", vln.groups[[j]]))
    }
  }
  return(patchwork::wrap_plots(c(dim.plots, feat.plots, vln.plots), 
                               widths = width,
                               heights = height,
                               ncol = ncol,
                               nrow = nrow,
                               design = design))
}


.getPlots <- function(sn.func, names){
  dim.ft  <- c("seurat.clusters")
  feat.ft <- c("nCount_RNA","PercentMito", "DoubletScore")
  vln.ft <- c("PercentMito", "DoubletScore")
  vln.groups <- c("seurat.clusters")
  plots.func <- plotUMAP(
         data = sn.func,
         dim.ft = dim.ft,
         feat.ft = feat.ft,
         vln.ft = NULL,
         vln.groups = NULL,
         ncol =1,
         font.size = 14,
         name = names)
  return(plots.func)
}

raw.plots <- lapply(names(sn), function(x){.getPlots(sn[[x]], names = x)})

names(raw.plots) <- names(sn)
.wrapPlots <- function(sn.name, plots.func){
    wrap_plots(plots.func[[sn.name]], ncol = 1 ) + 
    plot_annotation(title = sn.name,
                    theme = theme(plot.title = element_text(size = 18,
                                                            hjust = 0.5)))
}

wrapped.plots <- lapply(names(raw.plots), function(x){.wrapPlots(x, raw.plots)})

png("results/single_cell/qc_plots/t_premerge_seurats.png", width=1200, height=1200)

wrap_plots(wrapped.plots, ncol = length(raw.plots, clip = TRUE)) # +

dev.off()

```


```{r merge}

sn.merge <- merge(sn[[1]], sn[[2]]) |>
            merge(sn[[3]]) |>
            merge(sn[[4]])  |>
            merge(sn[[5]])  |>
            subset(isDoublet != "yes")

sn.merge <- ClusterSeurat(sn.merge, subset = F, regress.by = "origin", res = 0.1)

SaveH5Seurat(sn.merge, "data/processed/single_cell/merges/09072023_01res")
```

```{r merge visual}
png("results/single_cell/qc_plots/t_merged.png", width=1200, height=1200)
do_DimPlot(sn.merge, group.by ="origin")
dev.off()
```